FOREX_PAIRS = [

    # Major Forex
    "EURUSD",
    "GBPUSD",
    "USDJPY",
    "USDCHF",
    "USDCAD",
    "AUDUSD",
    "NZDUSD",

    # Minor / Cross Forex
    "EURJPY",
    "GBPJPY",
    "AUDJPY",
    "CADJPY",
    "CHFJPY",
    "EURGBP",
    "EURCHF",
    "EURAUD",
    "EURNZD",
    "EURCAD",
    "GBPAUD",
    "GBPCAD",
    "GBPCHF",
    "GBPNZD",
    "AUDCAD",
    "AUDCHF",
    "AUDNZD",
    "CADCHF",
    "NZDJPY",
    "NZDCHF",
    "NZDCAD",

    # OTC Pairs
    "EURUSD_otc",
    "GBPUSD_otc",
    "USDJPY_otc",
    "AUDUSD_otc",
    "NZDUSD_otc",
    "EURJPY_otc",
    "GBPJPY_otc",
    "AUDJPY_otc",
    "EURGBP_otc",
    "AUDCAD_otc",
    "AUDCHF_otc",
    "AUDNZD_otc",
    "CADCHF_otc",
    "NZDJPY_otc",
    "NZDCHF_otc",
    "NZDCAD_otc",
    "USDINR_otc",
    "USDBRL_otc",
    "USDMXN_otc",
    "USDZAR_otc",
    "USDARS_otc",
    "USDCOP_otc",
    "USDEGP_otc",
    "USDPHP_otc",
    "USDPKR_otc",
    "USDNGN_otc",
    "USDIDR_otc",
    "USDBDT_otc",
    "USDDZD_otc",
]